use std::{
    collections::HashMap,
    path::PathBuf,
    sync::{Mutex, OnceLock, RwLock},
    time::{Duration, Instant},
};

use base64::{
    engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD},
    Engine as _,
};
use ed25519_dalek::{Signature, VerifyingKey};
use rand::{Rng, RngCore};

/// Build-time embedded public key(s): comma-separated standard base64-encoded 32-byte Ed25519
/// keys. Set `TANGO_BRIDGE_PUBLIC_KEY` during `cargo build`.  Multiple keys are separated by
/// commas.
const PUBLIC_KEY_B64: Option<&str> = option_env!("TANGO_BRIDGE_PUBLIC_KEY");

/// Challenges expire after this duration.
pub const CHALLENGE_TTL: Duration = Duration::from_secs(3600);

/// A trusted Ed25519 public key together with its base64 representation.
pub struct PublicKey {
    /// Standard base64-encoded raw 32-byte key (as supplied in `TANGO_BRIDGE_PUBLIC_KEY`).
    pub b64: String,
    /// The parsed verifying key, ready for signature verification.
    pub key: VerifyingKey,
}

static PIN: OnceLock<RwLock<String>> = OnceLock::new();
/// Cached list of trusted public keys, initialised once in [`init`].
static PUBLIC_KEYS: OnceLock<Vec<PublicKey>> = OnceLock::new();

/// Map from challenge string to the `Instant` it was created.
static CHALLENGES: OnceLock<Mutex<HashMap<String, Instant>>> = OnceLock::new();

fn challenges() -> &'static Mutex<HashMap<String, Instant>> {
    CHALLENGES.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Return the cached slice of trusted public keys.
///
/// Returns an empty slice before [`init`] is called or when no keys are configured.
pub fn public_keys() -> &'static [PublicKey] {
    PUBLIC_KEYS.get().map(Vec::as_slice).unwrap_or(&[])
}

fn home_dir() -> PathBuf {
    #[cfg(windows)]
    {
        PathBuf::from(
            std::env::var("USERPROFILE")
                .or_else(|_| std::env::var("HOMEPATH"))
                .unwrap_or_default(),
        )
    }
    #[cfg(not(windows))]
    {
        PathBuf::from(std::env::var("HOME").unwrap_or_default())
    }
}

fn pin_file_path() -> PathBuf {
    home_dir().join(".android").join("tango-bridge.pin")
}

fn generate_pin() -> String {
    let n: u32 = rand::rng().random_range(0..1_000_000);
    format!("{:06}", n)
}

// ---------------------------------------------------------------------------
// Challenge management
// ---------------------------------------------------------------------------

/// Generate a fresh challenge string, record it in the in-memory store, and
/// return it.  The challenge is 16 random bytes encoded as URL-safe base64
/// (no padding), giving 128 bits of entropy.
///
/// Stale challenges (older than [`CHALLENGE_TTL`]) are pruned on every call.
pub fn generate_challenge() -> String {
    let mut bytes = [0u8; 16];
    rand::rng().fill_bytes(&mut bytes);
    let challenge = URL_SAFE_NO_PAD.encode(bytes);

    let mut map = challenges().lock().unwrap();
    let now = Instant::now();
    // Lazy cleanup of expired challenges.
    map.retain(|_, created| now.duration_since(*created) < CHALLENGE_TTL);
    map.insert(challenge.clone(), now);
    challenge
}

/// Validate a challenge.  Returns `true` if the challenge was generated by
/// this server within the last hour.  Unlike a one-time-use nonce, the same
/// challenge may be reused for multiple WebSocket connections until it expires,
/// so that clients can keep many connections open with a single
/// challenge/token pair.
fn validate_challenge(challenge: &str) -> bool {
    let map = challenges().lock().unwrap();
    let now = Instant::now();
    if let Some(&created) = map.get(challenge) {
        now.duration_since(created) < CHALLENGE_TTL
    } else {
        false
    }
}

// ---------------------------------------------------------------------------
// Public-key helpers
// ---------------------------------------------------------------------------

/// Parse a standard base64-encoded 32-byte Ed25519 public key into a [`PublicKey`].
fn parse_public_key(b64: &str) -> Option<PublicKey> {
    let bytes = STANDARD.decode(b64.trim()).ok()?;
    let array: [u8; 32] = bytes.try_into().ok()?;
    let key = VerifyingKey::from_bytes(&array).ok()?;
    Some(PublicKey {
        b64: b64.trim().to_string(),
        key,
    })
}

/// Build the list of trusted public keys from build-time and runtime sources.
///
/// Called once from [`init`].
fn load_public_keys() -> Vec<PublicKey> {
    let mut keys: Vec<PublicKey> = Vec::new();

    let mut add_from_list = |list: &str, source: &str| {
        for b64 in list.split(',') {
            let b64 = b64.trim();
            if b64.is_empty() {
                continue;
            }
            if let Some(pk) = parse_public_key(b64) {
                keys.push(pk);
            } else {
                eprintln!(
                    "tango-bridge: ignoring invalid Ed25519 public key in {} \
                     (expected standard base64-encoded 32-byte key): {}",
                    source, b64
                );
            }
        }
    };

    // Build-time embedded keys.
    if let Some(list) = PUBLIC_KEY_B64 {
        add_from_list(list, "build-time TANGO_BRIDGE_PUBLIC_KEY");
    }

    // Runtime keys (additional or alternative).
    if let Ok(list) = std::env::var("TANGO_BRIDGE_PUBLIC_KEY") {
        add_from_list(&list, "runtime TANGO_BRIDGE_PUBLIC_KEY");
    }

    keys
}

/// Load the PIN from the file (or generate and save a new one), and
/// initialise the list of trusted public keys.
/// Must be called once at startup before any other auth functions.
pub fn init() -> std::io::Result<()> {
    let path = pin_file_path();
    let pin = match std::fs::read_to_string(&path) {
        Ok(content) => {
            let s = content.trim().to_string();
            if s.is_empty() {
                let new_pin = generate_pin();
                std::fs::write(&path, &new_pin)?;
                new_pin
            } else {
                s
            }
        }
        Err(_) => {
            let new_pin = generate_pin();
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&path, &new_pin)?;
            new_pin
        }
    };
    PIN.get_or_init(|| RwLock::new(pin));
    PUBLIC_KEYS.get_or_init(load_public_keys);
    Ok(())
}

/// Return the current PIN code.
pub fn get_pin() -> String {
    PIN.get()
        .expect("auth::init() must be called before get_pin()")
        .read()
        .unwrap()
        .clone()
}

/// Generate a new PIN, persist it to the file, and return it.
pub fn regenerate_pin() -> String {
    let pin = generate_pin();
    let path = pin_file_path();
    let _ = std::fs::write(&path, &pin);
    if let Some(lock) = PIN.get() {
        *lock.write().unwrap() = pin.clone();
    }
    pin
}

/// Verify a public-key token: a URL-safe or standard base64-encoded Ed25519
/// signature of `challenge`, signed with the private key corresponding to any
/// of the configured public keys.
fn verify_token(challenge: &str, token: &str) -> bool {
    let keys = public_keys();
    if keys.is_empty() {
        return false;
    }

    // Accept URL-safe (no-padding) or standard base64 for the token.
    let Ok(sig_bytes) = URL_SAFE_NO_PAD
        .decode(token)
        .or_else(|_| STANDARD.decode(token))
    else {
        return false;
    };
    let Ok(sig_array): Result<[u8; 64], _> = sig_bytes.try_into() else {
        return false;
    };
    let signature = Signature::from_bytes(&sig_array);

    keys.iter()
        .any(|pk| pk.key.verify_strict(challenge.as_bytes(), &signature).is_ok())
}

/// Verify a PIN value against the stored PIN.
fn verify_pin(pin: &str) -> bool {
    PIN.get()
        .map(|lock| *lock.read().unwrap() == pin)
        .unwrap_or(false)
}

/// Return `true` if the query parameters contain valid credentials:
///
/// - `pin`: a valid 6-digit PIN, **or**
/// - `challenge` + `token`: a server-issued challenge that has not yet expired,
///   together with a valid Ed25519 signature of that challenge.
///
/// The same challenge may be used for multiple connections within its 1-hour
/// TTL window (it is not consumed on use).
pub fn is_authenticated(params: &HashMap<String, String>) -> bool {
    if let Some(pin) = params.get("pin") {
        if verify_pin(pin) {
            return true;
        }
    }

    if let (Some(challenge), Some(token)) = (params.get("challenge"), params.get("token")) {
        if validate_challenge(challenge) && verify_token(challenge, token) {
            return true;
        }
    }

    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn challenge_roundtrip() {
        let c = generate_challenge();
        // Valid challenge is accepted.
        assert!(validate_challenge(&c));
        // Same challenge can be reused within its TTL.
        assert!(validate_challenge(&c));
    }

    #[test]
    fn unknown_challenge_rejected() {
        assert!(!validate_challenge("notachallenge"));
    }
}
