name: "Build"

on:
  push:
    branches:
      - main
    paths:
      - .
  workflow_dispatch:

jobs:
  windows-x86:
    name: "Windows x86"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-cargo-

      - name: Install Rust toolchain
        run: rustup target add i686-pc-windows-msvc

      - name: Build
        run: cargo build --target i686-pc-windows-msvc --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "windows-x86"
          path: "target/i686-pc-windows-msvc/release/tango_bridge_rs.exe"

  windows-x64:
    name: "Windows x64"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-cargo-

      - name: Install Rust toolchain
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --target x86_64-pc-windows-msvc --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "windows-x64"
          path: "target/x86_64-pc-windows-msvc/release/tango_bridge_rs.exe"

  linux-x64:
    name: "Linux x64"
    runs-on: ubuntu-latest
    steps:
      - name: Install native dependencies
        run: sudo apt update && sudo apt install --no-install-recommends libgtk-3-dev libappindicator3-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-cargo-

      - name: Install Rust toolchain
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --target x86_64-unknown-linux-gnu --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "linux-x64"
          path: "target/x86_64-unknown-linux-gnu/release/tango_bridge_rs"

  macos-x64:
    name: "macOS x64"
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-cargo-

      - name: Install Rust toolchain
        run: rustup target add x86_64-apple-darwin

      - name: Build
        run: cargo build --target x86_64-apple-darwin --release
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13

      - run: cp target/x86_64-apple-darwin/release/tango_bridge_rs tango-bridge.app/Contents/MacOS/tango-bridge

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "macos-x64"
          path: "tango-bridge.app"

  macos-aarch64:
    name: "macOS aarch64"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ github.job }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-cargo-

      - name: Install Rust toolchain
        run: rustup target add aarch64-apple-darwin

      - name: Build
        run: cargo build --target aarch64-apple-darwin --release
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13

      - run: cp target/aarch64-apple-darwin/release/tango_bridge_rs tango-bridge.app/Contents/MacOS/tango-bridge

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "macos-aarch64"
          path: "tango-bridge.app"

  macos-universal:
    name: "macOS Universal"
    runs-on: macos-latest
    steps:
      - name: Download macos-x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-x64
          path: macos-x64-artifact

      - name: Download macos-aarch64 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-aarch64
          path: macos-aarch64-artifact

      - name: Create universal binary
        run: |
          lipo -create -output tango-bridge-universal macos-x64-artifact/tango-bridge.app/Contents/MacOS/tango-bridge macos-aarch64-artifact/tango-bridge.app/Contents/MacOS/tango-bridge
          cp tango-bridge-universal macos-x64-artifact/tango-bridge.app/Contents/MacOS/tango-bridge
          rm tango-bridge-universal

      - name: Upload macos-universal artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal
          path: macos-x64-artifact/tango-bridge.app
